export const QUERY_KEYS = {
  DOES_SESSION_EXIST: "DOES_SESSION_EXIST",
  USERS: "USERS",
  BUSINESSES: "BUSINESSES",
  CONNECTIONS: "CONNECTIONS",
  PANELS: "PANELS",
  CONNECTIONS_METADATA: "CONNECTIONS_METADATA",
  WIDGETS: "WIDGETS",
  REPORTS: "REPORTS",
};
