export const COPY = {
  "login.welcome": "¡Bienvenido!",
  "login.email": "Correo electrónico",
  "login.continue": "Continuar",
  "login.otp": "Código de verificación",
  "login.cta": "Iniciar sesión",
  "login.changeEmail": "Cambiar correo electrónico",
  "login.productCreatedBy": "Un producto creado por",
  "login.otpCreation.success": (email) =>
    `Código de verificación enviado a ${email}`,
  "login.otpConsumption.success": (name) => `Bienvenid@, ${name}`,

  "users.title": "Usuarios",
  "users.removal.success": "Eliminación realizada exitosamente",
  "users.creation.title": "Añadir Usuario",
  "users.creation.success": "Usuario creado exitosamente",
  "users.detail.title": "Detalle de Usuario",
  "users.detail.userRegistrationDate": "Fecha de registro",
  "users.detail.update.success": "Usuario actualizado exitosamente",
  "user.details.businessList.title": "Negocios",

  "connections.title": "Conexiones",
  "connections.removal.success": "Eliminación realizada exitosamente",
  "connections.creation.title": "Añadir Conexión",
  "connections.creation.google_analytics": "Google Analytics 4",
  "connections.creation.facebook_ads": "Facebook Ads",
  "connections.creation.success": "Conexión creada exitosamente",

  "businesses.title": "Negocios",
  "businesses.removal.success": "Eliminación realizada exitosamente",
  "businesses.creation.title": "Añadir Negocio",
  "businesses.creation.success": "Negocio creado exitosamente",
  "businesses.detail.title": "Detalle de Negocio",
  "businesses.detail.businessRegistrationDate": "Fecha de registro",
  "businesses.detail.update.success": "Negocio actualizado exitosamente",
  "businesses.detail.addEmployee": "Añadir Empleado",
  "businesses.detail.employees": "Empleados",
  "businesses.detail.addEmployee.modal.title": "Selecciona un empleado",
  "businesses.detail.addEmployee.modal.noEmployees":
    "No hay empleados disponibles en este momento",
  "businesses.detail.employeeAddition.success": "Empleado añadido exitosamente",
  "businesses.detail.employeeDeletion.success":
    "Eliminación realizada exitosamente",

  "panels.title": "Paneles",
  "panels.removal.success": "Eliminación realizada exitosamente",
  "panels.creation.title": "Añadir Panel",
  "panels.creation.success": "Panel añadido exitosamente",
  "panels.detail.title": "Detalle de Panel",
  "panels.detail.noWidgets": "Aún no hay widgets en este panel",
  "panels.detail.widget.create.success": "Widget añadido exitosamente",
  "panels.detail.widget.update.success": "Widget actualizado exitosamente",
  "panels.detail.widget.delete.success": "Eliminación realizada exitosamente",
  "panelNavbar.settings": "Ajustes",
  "panelNavbar.saveChanges": "Guardar",
  "panelNavbar.addWidget": "Añadir Widget",
  "panels.settings.title": "Ajustes de Panel",
  "panels.settings.panelRegistrationDate": "Fecha de registro",
  "panels.settings.update.success": "Panel actualizado exitosamente",

  "sidebar.logout": "Cerrar sesión",

  "searchBar.search": "Buscar...",

  "userList.user": "Usuario",
  "userList.role": "Función",
  "userList.role.admin": "Administrador",
  "userList.role.owner": "Propietario",
  "userList.role.employee": "Empleado",
  "userList.date": "Fecha",

  "employeeList.name": "Nombre",
  "employeeList.email": "Email",

  "businessList.company": "Compañía",
  "businessList.type": "Categoría",
  "businessList.type.service": "Empresa de Servicios",
  "businessList.type.commercial": "Empresa Comercial",
  "businessList.type.industrial": "Empresa Industrial",
  "businessList.description": "Descripción",

  "connectionList.connection": "Conexión",
  "connectionList.connection.facebook_ads": "Facebook Ads",
  "connectionList.connection.google_analytics": "Google Analytics 4",
  "connectionList.email": "Correo electrónico",
  "connectionList.date": "Fecha",

  "userForm.name": "Nombre",
  "userForm.email": "Correo electrónico",
  "userForm.role": "Función",
  "userForm.role.admin": "Administrador",
  "userForm.role.owner": "Propietario",
  "userForm.role.employee": "Empleado",
  "userForm.avatar": "Avatar",
  "userForm.notifyRegistration": "Notificar registro",
  "userForm.add": "Añadir",
  "userForm.save": "Guardar",

  "businessForm.name": "Nombre",
  "businessForm.type": "Categoría",
  "businessForm.type.service": "Empresa de Servicios",
  "businessForm.type.commercial": "Empresa Comercial",
  "businessForm.type.industrial": "Empresa Industrial",
  "businessForm.description": "Descripción",
  "businessForm.owner": "Propietario",
  "businessForm.owner.modal.title": "Selecciona un propietario",
  "businessForm.owner.noOwners": "Actualmente no hay propietarios registrados",
  "businessForm.owner.addOwner": "Añadir Propietario",
  "businessForm.avatar": "Avatar",
  "businessForm.owner.change": "Cambiar",
  "businessForm.add": "Añadir",
  "businessForm.save": "Guardar",

  "panelForm.name": "Nombre",
  "panelForm.description": "Descripción",
  "panelForm.business": "Negocio",
  "panelForm.business.modal.title": "Selecciona un negocio",
  "panelForm.business.change": "Cambiar",
  "panelForm.business.noBusinesses": "Actualmente no hay negocios registrados",
  "panelForm.business.addBusiness": "Añadir Negocio",
  "panelForm.add": "Añadir",
  "panelForm.save": "Guardar",

  "table.viewDetail": "Ver Detalle",
  "table.delete": "Eliminar",

  "panelListItem.businessName": (businessName) => `Negocio: ${businessName}`,
  "panelListItem.viewDetail": "Ver Detalle",
  "panelListItem.delete": "Eliminar",

  noDataYet: "Sin datos",

  "widgetMenu.selectConnectionType": "Selecciona un tipo de conexión",
  "widgetMenu.google_analytics": "Google Analytics 4",
  "widgetMenu.facebook_ads": "Facebook Ads",
  "widgetMenu.noConnections": "Actualmente no hay conexiones registradas",
  "widgetMenu.addConnection": "Añadir Conexión",

  "googleAnalyticsWidgetForm.property": "Propiedad",
  "googleAnalyticsWidgetForm.property.modal.title": "Selecciona una propiedad",
  "googleAnalyticsWidgetForm.metric": "Métrica",
  "googleAnalyticsWidgetForm.metric.modal.title": "Selecciona una métrica",
  "googleAnalyticsWidgetForm.chartType": "Tipo de gráfico",
  "googleAnalyticsWidgetForm.chartType.modal.title":
    "Selecciona un tipo de gráfico",
  "googleAnalyticsWidgetForm.timespan": "Periodo de tiempo",
  "googleAnalyticsWidgetForm.timespan.modal.title":
    "Selecciona un periodo de tiempo",
  "googleAnalyticsWidgetForm.dimension": "Dimensión",
  "googleAnalyticsWidgetForm.dimension.modal.title": "Selecciona una dimensión",
  "googleAnalyticsWidgetForm.title": "Título",
  "googleAnalyticsWidgetForm.add": "Añadir",
  "googleAnalyticsWidgetForm.save": "Guardar",

  "facebookAdsWidgetForm.adAccount": "Cuenta publicitaria",
  "facebookAdsWidgetForm.adAccount.modal.title":
    "Selecciona una cuenta publicitaria",
  "facebookAdsWidgetForm.metric": "Métrica",
  "facebookAdsWidgetForm.metric.modal.title": "Selecciona una métrica",
  "facebookAdsWidgetForm.chartType": "Tipo de gráfico",
  "facebookAdsWidgetForm.chartType.modal.title":
    "Selecciona un tipo de gráfico",
  "facebookAdsWidgetForm.timespan": "Periodo de tiempo",
  "facebookAdsWidgetForm.timespan.modal.title":
    "Selecciona un periodo de tiempo",
  "facebookAdsWidgetForm.dimension": "Dimensión",
  "facebookAdsWidgetForm.dimension.modal.title": "Selecciona una dimensión",
  "facebookAdsWidgetForm.title": "Título",
  "facebookAdsWidgetForm.add": "Añadir",
  "facebookAdsWidgetForm.save": "Guardar",

  "timespans.past7Days": "Últimos 7 días",
  "timespans.past14Days": "Últimos 14 días",
  "timespans.past28Days": "Últimos 28 días",
  "timespans.past30Days": "Últimos 30 días",
  "timespans.past90Days": "Últimos 90 días",
  "timespans.thisWeek": "Esta semana",
  "timespans.thisMonth": "Este mes",
  "timespans.thisYear": "Este año",

  "charts.number": "Número",
  "charts.line": "Línea",
  "charts.verticalBar": "Barras Verticales",
  "charts.horizontalBar": "Barras Horizontales",
  "charts.doughnut": "Donut",

  "filterInput.filter": "Filtro",

  "filterForm.field.modal.title": "Selecciona un campo",
  "filterForm.operator.modal.title": "Selecciona un operador",
  "filterForm.operator.equal": "Igual a",
  "filterForm.operator.not_equal": "No es igual a",
  "filterForm.operator.starts_with": "Empieza por",
  "filterForm.operator.ends_with": "Termina por",
  "filterForm.operator.contain": "Contiene",
  "filterForm.operator.not_contain": "No contiene",
  "filterForm.operand": "Expresión",
  "filterForm.add": "Añadir",
  "filterForm.save": "Guardar",

  "widget.edit": "Editar",
  "widget.delete": "Eliminar",

  "errors.requiredField": "Campo requerido",
  "errors.invalidEmail": "Correo electrónico no válido",
  "errors.unregisteredUser":
    "Este usuario no se encuentra registrado actualmente",
  "errors.unexpectedError":
    "Ha ocurrido un error inesperado, intentelo nuevamente",
  "errors.invalidOtpInput": (attemptsRemaining) =>
    `Código de verificación incorrecto. Intentos restantes: ${attemptsRemaining}`,
  "errors.otpExpired":
    "Este código de verificación ha expirado. Renegere uno nuevo e intentelo nuevamente",
};
